version: "3.3"

services:
    server:
        build:
            dockerfile: Dockerfile
        tty: true
        stdin_open: true
        priviledged: true
        container_name: server
        working_dir: /home/uekikatsuya/
        environment: 
            - GO!!!MODULE=on
        
