version: "3.3"

services:
    server:
        build: .
        tty: true
        stdin_open: true
        privileged: true
        container_name: server
        working_dir: /go/src/github.com/k-ueki/train-bot
        ports:
            - "8888:8888"
        environment: 
            - GO!!!MODULE=on
