version: "3.3"

services:
    server:
        build: .
        tty: true
        stdin_open: true
        privileged: true
        container_name: server
        working_dir: /train-bot
        environment: 
            - GO!!!MODULE=on
